// 03-vite/src/vue/App.vue
<template>
  <div class="app">
    <h2>App计数器： {{ count }}</h2>
    <button @click="increment">+1</button>
    <button @click="decrement">-1</button>
  </div>
</template>

<script setup>
import { ref } from "vue";

const count = ref(100);

function increment() {
  count.value++;
}
function decrement() {
  count.value--;
}
</script>

<style lang="less" scoped></style>

// 03-vite/src/react/App.jsx
import React, { useState } from "react";

function App() {
  const [count, setCount] = useState(100);

  return (
    <div className="app">
      <h2>React App计数器: {count}</h2>
      <button onClick={(e) => setCount(count + 1)}>+1</button>
      <button onClick={(e) => setCount(count - 1)}>-1</button>
    </div>
  );
}

export default App;
